SET session_replication_role = replica;

-- Shared integration definitions for all demos
-- Extracted from the original POC seed file

-- Integration definitions that are common across all business types
INSERT INTO "public"."poc_integrations" ("id", "name", "provider", "category", "icon_url", "input_schema", "output_schema", "config_schema", "requires_connection", "created_at", "updated_at") VALUES

-- Communication integrations
('e3c21175-b818-4c1c-9fc8-00a7525a4b6e', 'Slack: Send Channel Message', 'slack', 'Messaging', 'https://cdn.simpleicons.org/slack', '[{"id": "fld-channel", "name": "channel", "dataType": "string", "description": "Channel ID or name."}, {"id": "fld-message", "name": "message", "dataType": "string", "description": "Text message to send."}]', '[{"id": "fld-ts", "name": "messageTimestamp", "dataType": "string", "description": "Timestamp ID of the sent message."}]', NULL, true, '2025-04-15 10:31:58.543376+00', '2025-04-15 10:31:58.543376+00'),

('1051ee5f-2792-4a57-927d-2f1763e3b26b', 'Gmail: Send Email', 'gmail', 'Messaging', 'https://cdn.simpleicons.org/gmail', '[{"id": "fld-to", "name": "to", "dataType": "string", "description": "Recipient email address."}, {"id": "fld-subject", "name": "subject", "dataType": "string", "description": "Email subject."}, {"id": "fld-body", "name": "body", "dataType": "string", "description": "Email body (HTML/text)."}]', '[{"id": "fld-messageId", "name": "messageId", "dataType": "string", "description": "ID of the sent email."}]', NULL, true, '2025-04-15 10:31:58.543376+00', '2025-04-15 10:31:58.543376+00'),

('13db84e4-934a-4c6a-b024-489ad1f7f206', 'Twilio: Send SMS', 'twilio', 'Communication', 'https://cdn.simpleicons.org/twilio', '[{"id": "fld-to", "name": "to", "dataType": "string", "description": "Recipient phone number (E.164)."}, {"id": "fld-from", "name": "from", "dataType": "string", "description": "Twilio number or SID."}, {"id": "fld-body", "name": "body", "dataType": "string", "description": "SMS message body."}]', '[{"id": "fld-messageSid", "name": "messageSid", "dataType": "string", "description": "SID of the sent message."}]', NULL, true, '2025-04-15 10:31:58.543376+00', '2025-04-15 10:31:58.543376+00'),

-- Data storage integrations
('0d06e0ae-6f19-45ae-a1f2-42f97ea119de', 'Google Sheets: Add Row', 'google-sheets', 'Data Store', 'https://cdn.simpleicons.org/googlesheets', '[{"id": "fld-sheetId", "name": "spreadsheetId", "dataType": "string", "description": "Spreadsheet ID."}, {"id": "fld-sheetName", "name": "sheetName", "dataType": "string", "description": "Sheet name/tab."}, {"id": "fld-rowData", "name": "rowData", "dataType": "object", "description": "Row data object."}]', '[{"id": "fld-range", "name": "updatedRange", "dataType": "string", "description": "Range of the inserted row."}]', NULL, true, '2025-04-15 10:31:58.543376+00', '2025-04-15 10:31:58.543376+00'),

('bdc28a29-52a2-45ac-acea-834f5bbd76d6', 'Airtable: Create Record', 'airtable', 'Data Store', 'https://cdn.simpleicons.org/airtable', '[{"id": "fld-baseId", "name": "baseId", "dataType": "string", "description": "Airtable Base ID."}, {"id": "fld-tableId", "name": "tableId", "dataType": "string", "description": "Table ID or Name."}, {"id": "fld-fields", "name": "fields", "dataType": "object", "description": "Record field data."}]', '[{"id": "fld-recordId", "name": "recordId", "dataType": "string", "description": "ID of the created record."}]', NULL, true, '2025-04-15 10:31:58.543376+00', '2025-04-15 10:31:58.543376+00'),

-- AI integrations
('34caaab7-a888-4f7e-8cd2-84c9ea9dfd7b', 'OpenAI: Chat Completion', 'openai', 'AI', 'https://cdn.simpleicons.org/openai', '[{"id": "fld-prompt", "name": "prompt", "dataType": "string", "description": "Main user prompt."}, {"id": "fld-systemMsg", "name": "systemMessage", "dataType": "string", "optional": true, "description": "Optional system message."}]', '[{"id": "fld-response", "name": "responseText", "dataType": "string", "description": "Generated text response."}, {"id": "fld-usageTokens", "name": "tokensUsed", "dataType": "number", "description": "Tokens used."}]', '[{"id": "fld-model", "name": "model", "default": "gpt-4", "dataType": "string", "description": "Model (e.g., gpt-4)."}, {"id": "fld-temperature", "name": "temperature", "default": 0.7, "dataType": "number", "description": "Randomness (0.0-2.0)."}]', true, '2025-04-15 10:31:58.543376+00', '2025-04-15 10:31:58.543376+00'),

-- Utility integrations
('e8864274-9e6f-4a4f-867a-5c44d719f66d', 'HTTP: Make Request', 'http', 'Utility', 'https://cdn.simpleicons.org/webrtc', '[{"id": "fld-url", "name": "url", "dataType": "string", "description": "URL to request."}, {"id": "fld-method", "name": "method", "default": "GET", "dataType": "string", "description": "HTTP method."}, {"id": "fld-headers", "name": "headers", "dataType": "object", "optional": true, "description": "Request headers."}, {"id": "fld-body", "name": "body", "dataType": "any", "optional": true, "description": "Request body."}]', '[{"id": "fld-status", "name": "statusCode", "dataType": "number", "description": "Response status code."}, {"id": "fld-headers", "name": "responseHeaders", "dataType": "object", "description": "Response headers."}, {"id": "fld-body", "name": "responseBody", "dataType": "any", "description": "Response body."}]', NULL, false, '2025-04-15 10:31:58.543376+00', '2025-04-15 10:31:58.543376+00'),

-- File storage integrations  
('7d9dc4a0-3c6b-4b5d-9d7c-0bb4b2cc706c', 'Google Drive: Upload File', 'google-drive', 'File Storage', 'https://cdn.simpleicons.org/googledrive', '[{"id": "fld-folderId", "name": "folderId", "dataType": "string", "optional": true, "description": "Destination folder ID (optional)."}, {"id": "fld-fileName", "name": "fileName", "dataType": "string", "description": "Name for the uploaded file."}, {"id": "fld-fileContent", "name": "fileContent", "dataType": "string", "description": "File content (base64/reference)."}]', '[{"id": "fld-fileId", "name": "fileId", "dataType": "string", "description": "ID of the uploaded file."}]', NULL, true, '2025-04-15 10:31:58.543376+00', '2025-04-15 10:31:58.543376+00'),

-- Developer tools
('8c82446b-a123-4528-9cb3-9b7a22adf06b', 'GitHub: Create Issue', 'github', 'Developer Tools', 'https://cdn.simpleicons.org/github', '[{"id": "fld-owner", "name": "owner", "dataType": "string", "description": "Repo owner."}, {"id": "fld-repo", "name": "repo", "dataType": "string", "description": "Repo name."}, {"id": "fld-title", "name": "title", "dataType": "string", "description": "Issue title."}, {"id": "fld-body", "name": "body", "dataType": "string", "optional": true, "description": "Issue body."}]', '[{"id": "fld-issueNumber", "name": "issueNumber", "dataType": "number", "description": "Created issue number."}, {"id": "fld-issueUrl", "name": "issueUrl", "dataType": "string", "description": "URL of the issue."}]', NULL, true, '2025-04-15 10:31:58.543376+00', '2025-04-15 10:31:58.543376+00'),

('2ec49073-e8cf-424e-9011-881bf9014944', 'GitHub: Create Commit', 'github', 'Developer Tools', 'https://cdn.simpleicons.org/github', '[{"id": "fld-owner", "name": "owner", "dataType": "string", "description": "Repo owner."}, {"id": "fld-repo", "name": "repo", "dataType": "string", "description": "Repo name."}, {"id": "fld-branch", "name": "branch", "dataType": "string", "description": "Branch to commit to."}, {"id": "fld-message", "name": "message", "dataType": "string", "description": "Commit message."}, {"id": "fld-files", "name": "files", "dataType": "array", "description": "Array of file objects to commit, each with path and content properties."}]', '[{"id": "fld-commitSha", "name": "commitSha", "dataType": "string", "description": "SHA of the created commit."}, {"id": "fld-commitUrl", "name": "commitUrl", "dataType": "string", "description": "URL of the created commit."}]', NULL, true, '2025-04-21 15:04:53.535598+00', '2025-04-21 15:04:53.535598+00');

SET session_replication_role = origin; 